version: "1.0"
info:
  model: int-scaffold
packages:
- name: LDSGH1108Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: MultiplyPublicService
  version: "6.0"
  gitServerName: srcCtrl_shared_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
- name: XMLBuiltInServices
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: PubFlowShowcase
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
services:
- serviceName: project.ldsgh1108.integrations:bitbucketfs
  packages:
  - name: LDSGH1108Project
    version: "1.0"
  - name: XMLBuiltInServices
    version: "1.0"
  - name: MultiplyPublicService
    version: "6.0"
- serviceName: MultiplyPublicService:multiply_svc
  packages:
  - name: LDSGH1108Project
    version: "1.0"
  - name: XMLBuiltInServices
    version: "1.0"
  - name: MultiplyPublicService
    version: "6.0"
